name: 'Build Portable Binaries'

on:
  push:
    branches:
      - master

jobs:
  windows-build:
    name: 'Windows 32/64-bit'
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') != true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Package
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: '.'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: obs-websocket-http-Windows
          path: dist/windows
